# Generated by Django 4.2.21 on 2025-05-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0002_alter_devicestatus_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_mode', models.CharField(choices=[('all', 'Tüm Hafta'), ('weekday', 'Hafta İçi'), ('weekend', 'Hafta Sonu'), ('custom', 'Özel Günler')], default='all', max_length=10)),
                ('desired_temperature', models.FloatField(default=22.0)),
                ('presence_based', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_configs', to='sensors.room')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('heating', 'Isıtma'), ('fan', 'Fan')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedules.scheduleconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scheduleconfig',
            name='schedule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='schedules.scheduletype'),
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')])),
                ('schedule_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedules.scheduleconfig')),
            ],
            options={
                'unique_together': {('schedule_config', 'day')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='scheduleconfig',
            unique_together={('schedule_type', 'room')},
        ),
    ]
