# Generated by Django 4.2.21 on 2025-05-20 15:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_temperature', models.FloatField(default=24.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(40.0)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='schedules.day')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dayshours',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dayshours',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dayshours',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='hours',
            name='days',
        ),
        migrations.AlterUniqueTogether(
            name='scheduletime',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='is_fan_active',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='is_heating_active',
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='is_fan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='is_heating_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedules.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('name', 'user')},
        ),
        migrations.DeleteModel(
            name='Days',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.AddField(
            model_name='dayhour',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_hours', to='schedules.hour'),
        ),
        migrations.AlterField(
            model_name='scheduletime',
            name='day_hours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='schedules.dayhour'),
        ),
        migrations.DeleteModel(
            name='DaysHours',
        ),
        migrations.AlterUniqueTogether(
            name='dayhour',
            unique_together={('day', 'hour')},
        ),
    ]
