# Generated by Django 4.2.21 on 2025-05-20 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_devicestatus_options'),
        ('schedules', '0002_day_dayhour_hour_alter_dayshours_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_temperature', models.FloatField(default=24.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(40.0)])),
            ],
            options={
                'verbose_name_plural': 'Days Hours',
            },
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='day_hours',
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='schedule',
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='is_active',
            new_name='is_fan_active',
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='roomschedule',
            old_name='schedule',
            new_name='schedule_id',
        ),
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roomschedule',
            unique_together={('room_id', 'schedule_id')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='is_heating_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='DayHour',
        ),
        migrations.DeleteModel(
            name='ScheduleTime',
        ),
        migrations.AddField(
            model_name='dayshours',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_hours', to='schedules.day'),
        ),
        migrations.AddField(
            model_name='dayshours',
            name='hours_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_hours', to='schedules.hour'),
        ),
        migrations.AddField(
            model_name='dayshours',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_hours', to='schedules.schedule'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
