# Generated by Django 4.2.21 on 2025-05-20 15:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_dayshours_remove_scheduletime_day_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomschedule',
            old_name='is_fan_active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='roomschedule',
            name='is_heating_active',
        ),
        migrations.AlterUniqueTogether(
            name='dayshours',
            unique_together={('day', 'hours_id')},
        ),
        migrations.RemoveField(
            model_name='dayshours',
            name='desired_temperature',
        ),
        migrations.RemoveField(
            model_name='dayshours',
            name='schedule_id',
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desired_temperature', models.FloatField(default=24.0, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(40.0)])),
                ('is_heating_active', models.BooleanField(default=True)),
                ('is_fan_active', models.BooleanField(default=False)),
                ('day_hours_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='schedules.dayshours')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='schedules.schedule')),
            ],
            options={
                'unique_together': {('day_hours_id', 'schedule_id')},
            },
        ),
    ]
