# Generated by Django 4.2.21 on 2025-05-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_rename_is_fan_active_roomschedule_is_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduletime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='day_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='schedules.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletime',
            name='hour_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='schedules.hour'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='scheduletime',
            unique_together={('day_id', 'hour_id', 'schedule_id')},
        ),
        migrations.RemoveField(
            model_name='scheduletime',
            name='day_hours_id',
        ),
        migrations.DeleteModel(
            name='DaysHours',
        ),
    ]
