# Generated by Django 4.2.21 on 2025-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_devicestatus_options'),
        ('schedules', '0005_alter_scheduletime_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomschedule',
            unique_together={('room_id',)},
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
