# Generated by Django 4.2.21 on 2025-05-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'verbose_name': 'Device Status', 'verbose_name_plural': 'Device Statuses'},
        ),
    ]
