# Generated by Django 4.2.21 on 2025-05-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_devicestatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='fan_control_mode',
            field=models.CharField(choices=[('manual', 'Manuel Kontrol'), ('schedule', 'Program Kontrolü')], default='manual', max_length=10, verbose_name='Fan Kontrol Modu'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='heating_control_mode',
            field=models.CharField(choices=[('manual', 'Manuel Kontrol'), ('schedule', 'Program Kontrolü')], default='manual', max_length=10, verbose_name='Isıtma Kontrol Modu'),
        ),
    ]
