# Generated by Django 4.2.21 on 2025-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_devicestatus_fan_control_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatus',
            name='fan_control_mode',
            field=models.CharField(choices=[('manual', 'Manuel Kontrol'), ('schedule', 'Program Kontrolü')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='heating_control_mode',
            field=models.CharField(choices=[('manual', 'Manuel Kontrol'), ('schedule', 'Program Kontrolü')], default='manual', max_length=20),
        ),
    ]
